# Generated by Django 3.1.2 on 2021-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Titre')),
                ('description', models.CharField(max_length=50, verbose_name='Déscription')),
                ('article', models.CharField(max_length=250, verbose_name='Article')),
                ('visibility_date_limit', models.DateTimeField(verbose_name='Date limite de parution')),
                ('visible_only_by_admin', models.BooleanField(default=True, verbose_name="Article visible par l'administrateur uniquement")),
            ],
        ),
    ]
