# Generated by Django 3.1.2 on 2021-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(max_length=1000, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility_date_limit',
            field=models.DateField(verbose_name='Date limite de parution'),
        ),
    ]
